private_key: "your_private_key_here"
public_key: "your_public_key_here"
monitor_relays:
  - "wss://relay.example.com"
  - "wss://relay2.example.com"
frequency: 60 # in seconds, how often to check relays
outbox_relays:
  - "wss://relay.example.com"
  - "wss://relay2.example.com"
